// .archive/mobile-expo-20260827/src/features/generate/loras-field.tsx
import { Pressable, Text, View } from 'react-native';
import * as Haptics from 'expo-haptics';

import { Icon } from '@/components/ui/Icon';
import { useAppTheme } from '@/hooks/use-app-theme';
import type { EngineParam, LoraValue } from '@/types/api';

/**
 * LoRA 叠加字段（ParamSheet loras 型渲染器，M10.3，H3 引擎）
 * 语义对齐 Web ParamField loras 分支与 MiniProgram loras-field.vue：
 * - 多选 ≤3（后端 h3_studio.py _MAX_LORAS 同源，超出后端 422 兜底），选中追加 {name, strength:0.6}
 * - 强度区间/步进取注册表 param.min/max/step（H3LoraInput 0.5-1.0 / 0.05）；
 *   移动端无原生滑杆，以 +/- 步进器承载（步进即注册表 step，结果规整 2 位小数）
 * - options 为空 = H3 实例不可达/无 LoRA（注册表声明态兜底），显式提示不静默吞掉
 */

/** 后端 h3_studio.py _MAX_LORAS 同一约束 */
const MAX_LORAS = 3;
/** H3LoraInput 缺省强度（作者推荐，与 generate-screen LORA_DEFAULT_STRENGTH 同源；本地常量避免组件反向依赖屏幕模块） */
const DEFAULT_STRENGTH = 0.6;

export interface LorasFieldProps {
  param: EngineParam;
  /** 表单值载体：LoraValue 数组；脏值（非数组）按空数组渲染 */
  value: LoraValue[];
  onChange: (value: LoraValue[]) => void;
  testID?: string;
}

export function LorasField({ param, value, onChange, testID = 'loras-field' }: LorasFieldProps) {
  const { colors, radius, spacing, typography } = useAppTheme();

  const options = param.options ?? [];
  const selected: LoraValue[] = Array.isArray(value) ? value : [];

  const strengthMin = param.min ?? 0.5;
  const strengthMax = param.max ?? 1.0;
  const strengthStep = param.step ?? 0.05;

  const isOn = (name: string) => selected.some((l) => l && l.name === name);
  const strengthOf = (name: string): number => {
    const s = selected.find((l) => l && l.name === name)?.strength;
    return typeof s === 'number' && Number.isFinite(s) ? s : DEFAULT_STRENGTH;
  };
  /** 已达上限且未选中的项禁止再选（capped 只挡未选项，已选项仍可取消） */
  const isCapped = (name: string) => !isOn(name) && selected.length >= MAX_LORAS;

  const toggle = (name: string) => {
    void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    if (isOn(name)) {
      onChange(selected.filter((l) => l.name !== name));
      return;
    }
    if (selected.length >= MAX_LORAS) return;
    onChange([...selected, { name, strength: DEFAULT_STRENGTH }]);
  };

  /** 强度步进：±step 后钳到 [min,max] 并规整 2 位小数（0.6+0.05 浮点误差兜底） */
  const bump = (name: string, dir: 1 | -1) => {
    void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    onChange(
      selected.map((l) => {
        if (l.name !== name) return l;
        const clamped = Math.min(strengthMax, Math.max(strengthMin, strengthOf(name) + dir * strengthStep));
        return { ...l, strength: Math.round(clamped * 100) / 100 };
      }),
    );
  };

  const captionStyle = {
    color: colors.textSecondary,
    fontSize: typography.caption.fontSize,
    lineHeight: typography.caption.lineHeight,
  } as const;

  const stepButtonStyle = {
    width: 32,
    height: 32,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg,
    alignItems: 'center',
    justifyContent: 'center',
  } as const;

  return (
    <View style={{ marginTop: spacing[5] }} testID={testID}>
      <Text style={{ marginBottom: spacing[2], ...captionStyle }}>{param.label}</Text>

      {options.length === 0 ? (
        <Text testID={`${testID}-empty`} style={captionStyle}>
          引擎实例上暂无可用 LoRA
        </Text>
      ) : (
        <View style={{ gap: spacing[2] }}>
          {options.map((opt) => {
            const on = isOn(opt.value);
            const capped = isCapped(opt.value);
            return (
              <View key={opt.value} style={{ gap: spacing[1] }}>
                <Pressable
                  accessibilityRole="button"
                  accessibilityState={{ selected: on, disabled: capped }}
                  disabled={capped}
                  onPress={() => toggle(opt.value)}
                  testID={`${testID}-opt-${opt.value}`}
                  style={{
                    flexDirection: 'row',
                    alignItems: 'center',
                    gap: spacing[2],
                    minHeight: 44,
                    paddingHorizontal: spacing[3],
                    borderWidth: 1,
                    borderRadius: radius.md,
                    borderColor: on ? colors.accent : colors.border,
                    backgroundColor: on ? colors.accentSoft : colors.bg,
                    opacity: capped ? 0.5 : 1,
                  }}
                >
                  {/* 选中勾选框 */}
                  <View
                    style={{
                      width: 20,
                      height: 20,
                      borderWidth: 1,
                      borderRadius: radius.sm,
                      borderColor: on ? colors.accent : colors.border,
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}
                  >
                    {on ? <Icon name="Check" size={14} color={colors.accent} /> : null}
                  </View>
                  <Text
                    numberOfLines={1}
                    style={{
                      flex: 1,
                      color: on ? colors.accent : colors.text,
                      fontSize: typography.body.fontSize,
                      lineHeight: typography.body.lineHeight,
                      fontWeight: on ? '600' : '400',
                    }}
                  >
                    {opt.label}
                  </Text>
                  {opt.nsfw ? (
                    <Text
                      style={{
                        fontSize: 10,
                        color: colors.danger,
                        borderWidth: 1,
                        borderColor: colors.danger,
                        borderRadius: radius.sm,
                        paddingHorizontal: spacing[1],
                      }}
                    >
                      R18
                    </Text>
                  ) : null}
                </Pressable>

                {/* 强度步进器：仅选中项展示 */}
                {on ? (
                  <View
                    testID={`${testID}-strength-${opt.value}`}
                    style={{
                      flexDirection: 'row',
                      alignItems: 'center',
                      gap: spacing[3],
                      paddingHorizontal: spacing[2],
                    }}
                  >
                    <Pressable
                      accessibilityRole="button"
                      accessibilityLabel={`${opt.label} 强度减`}
                      onPress={() => bump(opt.value, -1)}
                      testID={`${testID}-strength-${opt.value}-minus`}
                      style={stepButtonStyle}
                    >
                      <Icon name="Minus" size={16} color={colors.text} />
                    </Pressable>
                    <Text style={{ flex: 1, textAlign: 'center', ...captionStyle }}>
                      {strengthOf(opt.value).toFixed(2)}
                    </Text>
                    <Pressable
                      accessibilityRole="button"
                      accessibilityLabel={`${opt.label} 强度加`}
                      onPress={() => bump(opt.value, 1)}
                      testID={`${testID}-strength-${opt.value}-plus`}
                      style={stepButtonStyle}
                    >
                      <Icon name="Plus" size={16} color={colors.text} />
                    </Pressable>
                  </View>
                ) : null}
              </View>
            );
          })}
          <Text style={[captionStyle, { opacity: 0.75 }]}>{`已选 ${selected.length}/${MAX_LORAS}`}</Text>
        </View>
      )}

      {param.hint ? (
        <Text style={{ marginTop: spacing[1], ...captionStyle, opacity: 0.8 }}>{param.hint}</Text>
      ) : null}
    </View>
  );
}

// MiniProgram/src/components/business/loras-field.vue
<script setup lang="ts">
/**
 * LoRA 叠加字段（loras 类型参数，H3 引擎）：多选（≤3）+ 单项强度滑杆
 * 语义对齐 Web ParamField loras 分支：选中追加 {name, strength:0.6}，滑杆调强度
 * 强度区间/步进取注册表 param.min/max/step（后端 H3LoraInput 0.5-1.0，缺省 0.6）
 * options 为空 = H3 实例不可达/无 LoRA（注册表声明态兜底），显式提示不静默吞掉
 */
import { computed } from 'vue';

import Icon from '@/components/ui/icon.vue';
import { useAppTheme } from '@/composables/use-app-theme';
import type { EngineParam, LoraValue } from '@/types/api';
import { LORA_DEFAULT_STRENGTH } from '@/utils/build-request';

/** 后端 h3_studio.py _MAX_LORAS 同一约束 */
const MAX_LORAS = 3;

const props = defineProps<{
  param: EngineParam;
  modelValue: unknown;
}>();

const emit = defineEmits<{
  change: [value: LoraValue[]];
}>();

const { palette } = useAppTheme();

const options = computed(() => props.param.options ?? []);
const selected = computed<LoraValue[]>(() =>
  Array.isArray(props.modelValue) ? (props.modelValue as LoraValue[]) : [],
);

const strengthMin = computed(() => props.param.min ?? 0.5);
const strengthMax = computed(() => props.param.max ?? 1.0);
const strengthStep = computed(() => props.param.step ?? 0.05);

function isOn(name: string): boolean {
  return selected.value.some((l) => l.name === name);
}

function strengthOf(name: string): number {
  return selected.value.find((l) => l.name === name)?.strength ?? LORA_DEFAULT_STRENGTH;
}

/** 已达上限且未选中的项禁止再选（后端 max_length=3 → 422 兜底） */
function isCapped(name: string): boolean {
  return !isOn(name) && selected.value.length >= MAX_LORAS;
}

function toggle(name: string) {
  if (isOn(name)) {
    emit(
      'change',
      selected.value.filter((l) => l.name !== name),
    );
    return;
  }
  if (selected.value.length >= MAX_LORAS) return;
  emit('change', [...selected.value, { name, strength: LORA_DEFAULT_STRENGTH }]);
}

function onStrength(name: string, e: { detail: { value: number } }) {
  const strength = Number(e.detail.value);
  if (!Number.isFinite(strength)) return;
  emit(
    'change',
    selected.value.map((l) => (l.name === name ? { ...l, strength } : l)),
  );
}
</script>

<template>
  <view class="loras-field">
    <text
      v-if="options.length === 0"
      class="loras-field__empty"
    >
      引擎实例上暂无可用 LoRA
    </text>

    <template v-else>
      <view
        v-for="opt in options"
        :key="opt.value"
        class="loras-field__item"
      >
        <view
          class="loras-field__row"
          :class="{
            'loras-field__row--active': isOn(opt.value),
            'loras-field__row--capped': isCapped(opt.value),
          }"
          hover-class="loras-field__row--pressed"
          @tap="toggle(opt.value)"
        >
          <view
            class="loras-field__check"
            :class="{ 'loras-field__check--active': isOn(opt.value) }"
          >
            <Icon
              v-if="isOn(opt.value)"
              name="check"
              :size="28"
              color="var(--color-accent)"
            />
          </view>
          <text
            class="loras-field__name"
            number-of-lines="1"
          >
            {{ opt.label }}
          </text>
          <text
            v-if="opt.nsfw"
            class="loras-field__nsfw"
          >
            R18
          </text>
        </view>

        <view
          v-if="isOn(opt.value)"
          class="loras-field__strength"
        >
          <slider
            class="loras-field__slider"
            :min="strengthMin"
            :max="strengthMax"
            :step="strengthStep"
            :value="strengthOf(opt.value)"
            :active-color="palette.accent"
            :block-size="20"
            @change="(e: any) => onStrength(opt.value, e)"
            @changing="(e: any) => onStrength(opt.value, e)"
          />
          <text class="loras-field__strength-val">
            {{ strengthOf(opt.value).toFixed(2) }}
          </text>
        </view>
      </view>

      <text class="loras-field__count">
        已选 {{ selected.length }}/{{ MAX_LORAS }}
      </text>
    </template>
  </view>
</template>

<style scoped lang="scss">
.loras-field {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);

  &__empty {
    font-size: var(--font-caption);
    color: var(--color-text-secondary);
  }

  &__item {
    display: flex;
    flex-direction: column;
    gap: var(--space-1);
  }

  &__row {
    display: flex;
    flex-direction: row;
    align-items: center;
    gap: var(--space-2);
    min-height: 64rpx;
    padding: 0 var(--space-3);
    border: 1rpx solid var(--color-border);
    border-radius: var(--radius-md);

    &--active {
      border-color: var(--color-accent);
      background: var(--color-accent-soft);
    }

    &--capped {
      opacity: 0.5;
    }

    &--pressed {
      opacity: 0.8;
    }
  }

  &__check {
    width: 36rpx;
    height: 36rpx;
    border: 1rpx solid var(--color-border);
    border-radius: var(--radius-sm);
    display: flex;
    align-items: center;
    justify-content: center;

    &--active {
      border-color: var(--color-accent);
    }
  }

  &__name {
    flex: 1;
    font-size: var(--font-caption);
    color: var(--color-text);
    overflow: hidden;
  }

  &__nsfw {
    font-size: 20rpx;
    color: var(--color-danger);
    border: 1rpx solid var(--color-danger);
    border-radius: var(--radius-sm);
    padding: 0 var(--space-1);
  }

  &__strength {
    display: flex;
    flex-direction: row;
    align-items: center;
    gap: var(--space-3);
    padding: 0 var(--space-2);
  }

  &__slider {
    flex: 1;
    margin: 0;
  }

  &__strength-val {
    min-width: 72rpx;
    text-align: right;
    font-size: var(--font-caption);
    color: var(--color-text-secondary);
  }

  &__count {
    font-size: var(--font-caption);
    color: var(--color-text-secondary);
    opacity: 0.75;
  }
}
</style>
